language: php
sudo: false

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

os:
  - linux
  - osx

services:
  - memcache  # will start memcache service
  - memcached # will start memcached service

env:
  - DOCTRINE_VERSION=v1.1 ZEND_VERSION=2.1.* DESARROLLA_VERSION=1.4.0 ZETA_VERSION=1.6
  - DOCTRINE_VERSION=v1.2.0 ZEND_VERSION=2.2.* DESARROLLA_VERSION=1.5.0 ZETA_VERSION=dev-master
  - DOCTRINE_VERSION=v1.3.0 ZEND_VERSION=2.3.* DESARROLLA_VERSION=1.6.0 ZETA_VERSION=dev-master
  - DOCTRINE_VERSION=1.3.1 ZEND_VERSION=2.4.0 DESARROLLA_VERSION=1.7.0 ZETA_VERSION=dev-master
  - DOCTRINE_VERSION=1.4.0 ZEND_VERSION=2.4.1 DESARROLLA_VERSION=1.7.1 ZETA_VERSION=dev-master
  - DOCTRINE_VERSION=1.4.1 ZEND_VERSION=2.4.2 DESARROLLA_VERSION=1.8.0 ZETA_VERSION=dev-master
  - DOCTRINE_VERSION=1.5.*@dev ZEND_VERSION=2.5.0 DESARROLLA_VERSION=1.8.0 ZETA_VERSION=dev-master
  - DOCTRINE_VERSION=dev-master ZEND_VERSION=2.5.1 DESARROLLA_VERSION=dev-master ZETA_VERSION=dev-master
  - DOCTRINE_VERSION=dev-master ZEND_VERSION=2.5.2 DESARROLLA_VERSION=dev-master ZETA_VERSION=dev-master
  - DOCTRINE_VERSION=dev-master ZEND_VERSION=dev-master DESARROLLA_VERSION=dev-master ZETA_VERSION=dev-master

matrix:
  allow_failures:
    - php: hhvm
    - env: DOCTRINE_VERSION=dev-master ZEND_VERSION=dev-master DESARROLLA_VERSION=dev-master ZETA_VERSION=dev-master

before_script:
  - if [ "`phpenv version-name`" != "hhvm" ] && [ "`phpenv version-name`" != "hhvm-nightly" ]; then echo 'date.timezone = "Europe/Paris"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [ "`phpenv version-name`" == "5.3" ] || [ "`phpenv version-name`" == "5.4" ]; then echo "extension = apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [ "`phpenv version-name`" != "hhvm" ] && [ "`phpenv version-name`" != "hhvm-nightly" ]; then echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [ "`phpenv version-name`" != "hhvm" ] && [ "`phpenv version-name`" != "hhvm-nightly" ]; then echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [ "`phpenv version-name`" == "5.5" ] || [ "`phpenv version-name`" == "5.6" ]; then echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [ "`phpenv version-name`" == "5.5" ] || [ "`phpenv version-name`" == "5.6" ]; then echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - composer self-update
  - composer require --no-update phpunit/phpunit:*
  - composer require --no-update mikey179/vfsStream:dev-master
  - composer require --no-update zetacomponents/cache:${ZETA_VERSION}
  - composer require --no-update doctrine/cache:${DOCTRINE_VERSION}
  - composer require --no-update zendframework/zend-stdlib:${ZEND_VERSION}
  - composer require --no-update zendframework/zend-eventmanager:${ZEND_VERSION}
  - composer require --no-update zendframework/zend-servicemanager:${ZEND_VERSION}
  - composer require --no-update zendframework/zend-cache:${ZEND_VERSION}
  - composer require --no-update desarrolla2/cache:${DESARROLLA_VERSION}
  - composer update --no-dev -o --prefer-source
  - php vendor/autoload.php

script:
  - phpunit --configuration tests/phpunit.xml --coverage-text --coverage-clover=coverage.clover --colors --verbose

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
